name: "android-build"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  compile-and-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Run tests"
        run: "./gradlew test deviceCheck"
      - name: "Create release apk"
        run: "./gradlew assembleRelease"
      - name: "Show all files"
        run: "find ${GITHUB_WORKSPACE} -type f"
      - name: "Copy APK"
        uses: "actions/upload-artifact@v2"
        with:
          name: "tahoe-lafs-android"
          path: "./app/build/outputs/apk/release/app-release-unsigned.apk"
          if-no-files-found: "error"
